### ISSUE TITLE
Dev Task1: Setup django and deploy

### ISSUE THREAD

**Issue by vishalchandrachapa** [Vishalchapa/task-manager-app#1]
As a **developer**, I can **setup django**, so that **i can start building the task manager app projects**
**Acceptance Criteria**
* Setup django
* Setup global base.html in templates
* Setup index.html in core app
* Deploy to heroku
**Task**
- [x] Install django, gunicorn and migrate
- [x] Configure settings
- [x] Install postgressql and add to list of installed apps
- [x] Create procfile and env file and include necessary code details
- [x] Install cloudinary and add to settings
- [x] Install whitenoise and configure
- [x] Create base.html and index.html and configure url paths and views
